// 由GOVCL UI设计器自动生成，不要编辑。
// Automatically generated by the GOVCL UI designer, do not edit.
package main

import (
    "gitee.com/ying32/govcl/vcl"
)

type TForm1 struct {
    *vcl.TForm
    Button1      *vcl.TButton
    ComboBox1    *vcl.TComboBox
    ListBox1     *vcl.TListBox
    CheckBox1    *vcl.TCheckBox
    Edit1        *vcl.TEdit
    Memo1        *vcl.TMemo
    Button2      *vcl.TButton
    TreeView1    *vcl.TTreeView
    ListView1    *vcl.TListView
    StatusBar1   *vcl.TStatusBar
    PageControl1 *vcl.TPageControl
    Panel1       *vcl.TPanel
    Button3      *vcl.TButton
    Button4      *vcl.TButton
    MainMenu1    *vcl.TMainMenu
    MenuItem13   *vcl.TMenuItem
    MenuItem14   *vcl.TMenuItem
    MenuItem15   *vcl.TMenuItem
    MenuItem16   *vcl.TMenuItem
    MenuItem26   *vcl.TMenuItem
    MenuItem25   *vcl.TMenuItem
    MenuItem27   *vcl.TMenuItem
    MenuItem28   *vcl.TMenuItem
    MenuItem29   *vcl.TMenuItem
    MenuItem17   *vcl.TMenuItem
    MenuItem18   *vcl.TMenuItem
    MenuItem30   *vcl.TMenuItem
    MenuItem31   *vcl.TMenuItem
    MenuItem33   *vcl.TMenuItem
    MenuItem35   *vcl.TMenuItem
    MenuItem36   *vcl.TMenuItem
    MenuItem37   *vcl.TMenuItem
    MenuItem38   *vcl.TMenuItem
    MenuItem39   *vcl.TMenuItem
    MenuItem19   *vcl.TMenuItem
    MenuItem20   *vcl.TMenuItem
    MenuItem21   *vcl.TMenuItem
    MenuItem23   *vcl.TMenuItem
    MenuItem24   *vcl.TMenuItem
    MenuItem22   *vcl.TMenuItem
    MenuItem32   *vcl.TMenuItem
    MenuItem34   *vcl.TMenuItem
    OpenDialog1  *vcl.TOpenDialog
    ActionList1  *vcl.TActionList
    ImageList1   *vcl.TImageList
    PopupMenu1   *vcl.TPopupMenu
    MenuItem1    *vcl.TMenuItem
    MenuItem2    *vcl.TMenuItem
    MenuItem10   *vcl.TMenuItem
    MenuItem11   *vcl.TMenuItem
    MenuItem12   *vcl.TMenuItem
    MenuItem3    *vcl.TMenuItem
    MenuItem4    *vcl.TMenuItem
    MenuItem5    *vcl.TMenuItem
    MenuItem6    *vcl.TMenuItem
    MenuItem7    *vcl.TMenuItem
    MenuItem8    *vcl.TMenuItem
    MenuItem9    *vcl.TMenuItem
    Button5      *vcl.TButton
}

var Form1 *TForm1




// vcl.Application.CreateFormFromFile("Form1.gfm", &Form1)
