// 由GOVCL UI设计器自动生成，不要编辑。
// Automatically generated by the GOVCL UI designer, do not edit.
package main

import (
    "gitee.com/ying32/govcl/vcl"
)

type TForm2 struct {
    *vcl.TForm
    RadioGroup1 *vcl.TRadioGroup
    Button1     *vcl.TButton
    Button2     *vcl.TButton
}

var Form2 *TForm2




// vcl.Application.CreateFormFromFile("Form2.gfm", &Form2)
